[project]
name = "aidams-lab1-tanios-tanguy-lebard-lebihan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "camille-tanguy", email = "camille.tanguy@student-cs.fr" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "plotly>=7.1.0",
]

[project.scripts]
aidams-lab1-tanios-tanguy-lebard-lebihan = "aidams_lab1_tanios_tanguy_lebard_lebihan:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
